version: "2"
services:
  web:
    build: "./web"
    ports:
      - "3333:3333"
    expose: 
      - "3333"
    environment: 
      - PROD=false
      - PORT=3333
    depends_on:
      - db
    volumes:
      - "./web:/app"
  db:
    restart: "always"
    build: "./db"
    ports:
      - "6000:5432"
